// For Logging in user
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';


// For Registering user
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCESS = 'REGISTER_SUCCESS';

// For syncing Contacts to db
export const SYNC_CONTACTS_REQUEST = 'SYNC_CONTACTS';
export const SYNC_CONTACTS_SUCCESS = 'SYNC_CONTACTS_SUCCESS';
export const SYNC_CONTACTS_FAILED = 'SYNC_CONTACTS_FAILED';

// For fetching contacts
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED';


// For syncing messages to db
export const MESSAGES_SYNC_REQUEST = 'MESSAGES_SYNC_REQUEST';
export const MESSAGES_SYNC_SUCCESS = 'MEESSAGES_SYNC_SUCCESS';
export const MESSAGES_SYNC_FAILED = 'MESSAGES_SYNC_FAILED';

// For fetching messages
export const MESSAGES_FETCH_REQUEST = 'MESSAGES_FETCH_REQUEST';
export const MESSAGES_FETCH_SUCCESS = 'MEESSAGES_FETCH_SUCCESS';
export const MESSAGES_FETCH_FAILED = 'MESSAGES_FETCH_FAILED';

